price_is_now_right/models.py
from flask_login import UserMixin
from flask_wtf import FlaskForm 
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import InputRequired, Email, Length
from .extensions import db

class User(UserMixin, db.Model): # UserMixin provides default implementations for the methods flask-login expects users to have
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(80))

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    userId = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    title = db.Column(db.String(), nullable=False)
    productURL = db.Column(db.String(), nullable=False)
    currentPrice = db.Column(db.Integer)
    userBudget = db.Column(db.Integer, nullable=False)

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(min=4, max=15)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=80)])
    remember = BooleanField('Remember Me')

class RegisterForm(FlaskForm):
    email = StringField('Gmail', validators=[InputRequired(), Email(message='Invalid email'), Length(max=50)])
    username = StringField('Username', validators=[InputRequired(), Length(min=4, max=15)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=80)])

class PriceTrackForm(FlaskForm):
    url = StringField('URL on eBay', validators=[InputRequired()])
    userBudget = StringField('My Budget', validators=[InputRequired()])

price_is_now_right/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate
from flask_login import LoginManager

from .commands import create_tables
from .models import User
from .routes import main
from .extensions import db, login_manager

def create_app(config_file='settings.py'):
    # Instantiation
    app = Flask(__name__)
    app.config.from_pyfile('settings.py')
    bootstrap = Bootstrap(app) # allows use of flask-bootstrap
    db.init_app(app)
    migrate = Migrate(app, db)
    login_manager.init_app(app)
    login_manager.login_view = 'main.login'

    # connects flask-login and database
    # provide user_loader callback
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    app.register_blueprint(main)

    app.cli.add_command(create_tables)

    return app

#if __name__ == '__main__':
 #   app.run(debug=True)

price_is_now_right/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User, Product, LoginForm, RegisterForm, PriceTrackForm
from .extensions import db
from .functions import check_price_initial, send_mail

main = Blueprint('main', __name__)

# homepage
@main.route('/')
def index():
    return render_template('index.html')

# login page
@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():  #checks if form has been submitted
        user = User.query.filter_by(username=form.username.data).first() # getting user from form
        if user: # checks if the user exists in the database
            if check_password_hash(user.password, form.password.data):  # checks if password is correct (imported method)
                login_user(user, remember=form.remember.data)
                return redirect(url_for('main.dashboard'))
        return redirect(url_for('main.login'))
    return render_template('login.html', form=form)

# signup page (similar to login route)
@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256') # hashing the password; sha236 generates a hash that is 80 characters long
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_password) # creating a new user
        # adding and commit to database
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.login'))
    return render_template('signup.html', form=form)

# dashboard page or the page with the price tracking form
@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    form = PriceTrackForm()
    if form.validate_on_submit():        
        if (check_price_initial() == 0):  # check_price_initial() == 0 means that the price is under the budget and an email was sent
            return redirect(url_for('main.index'))
        else:
            form = PriceTrackForm()
            return render_template('dashboard.html', form=form) # price is higher than budget               
    return render_template('dashboard.html', form=form)

# wishlist page with list of user's tracking products
@main.route('/wishlist', methods=['GET', 'POST'])
@login_required
def wishlist():
    id = current_user.id
    productList = Product.query.filter_by(userId=id).all()
    return render_template('wishlist.html', productList=productList)

# for removing an item from the wishlist
@main.route('/delete/<id>')
@login_required
def delete(id):
    remove_product = Product.query.filter_by(id=int(id)).first()
    db.session.delete(remove_product)
    db.session.commit()
    return redirect(url_for('main.wishlist'))

# for adjusting the budget for an item in the wishlist
@main.route('/budget/<id>', methods=['POST'])
@login_required
def budget(id):
    new_budget = request.form.get("new_budget")
    update_product = Product.query.filter_by(id=int(id)).first()    
    update_product.userBudget = new_budget
    db.session.commit()
    return redirect(url_for('main.wishlist'))

@main.route('/logout')
@login_required #cannot access directly must login first
def logout():
    logout_user() # method from flask-login
    return redirect(url_for('main.index'))

price_is_now_right/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
        {% endblock %}
        <title>{% block title %}{% endblock %}</title>

        {% endblock %}
    </head>
    <body>
        <!-- Your page content -->
        {% block content %}{% endblock %}

        {% block scripts %}
            <!-- Optional JavaScript -->
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>

price_is_now_right/templates/dashboard.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_field %}

{% block title %}
Dashboard | The Price is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='dashboard.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('main.index') }}">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.wishlist') }}">Wishlist</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.logout') }}">Log Out</a></li>
    </ul>
  </div>
</nav>

<br>

<!-- form for price tracking-->
<div class="container-fluid text-center">
    <form class="form-track" method="POST" onsubmit="change()" method="POST" action="/dashboard">
        {{ form.csrf_token() }}  <!--cross site request forgery token for flask-wtf-->
        {{ render_field(form.url) }} <!--getting info from form fields-->
        {{ render_field(form.userBudget) }}
        <button class="btn btn-primary btn-lg" type="submit" id="enter">Start Price Tracking!</button>
    </form>
    <br>
    <img class="tracker" src="../static/tracker.gif">
</div>

{%- block footer %}

{%- endblock footer %}

<script>
    function change() {
        alert("Price Tracking...\nYou will receive an email once the price goes down!");
    }
</script>

</div>

{% endblock %}

price_is_now_right/templates/index.html
{% extends "base.html" %}

{% block title %}Home | The Price Is Now Right{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='index.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
{{super()}}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if current_user.is_anonymous %}
      <ul class="navbar-nav ml-auto">                
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.login') }}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.signup') }}">Sign Up</a></li> 
      </ul>
    {% endif %}
    {% if current_user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.wishlist') }}">Wishlist</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.logout') }}">Log Out</a></li>
      </ul>
    {% endif %}  
  </div>
</nav>

<br><br><br><br>
<div class="container-fluid">
  <div class="container-fluid col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <h3 class="describe">Never miss a discount on things you want!</h3>
    <br>
    <a class="start" 
      {% if current_user.is_anonymous %}
      href="{{ url_for('main.login') }}"
      {% else %}
      href="{{ url_for('main.dashboard') }}"
      {% endif %}>
      <button class="startbutton btn btn-lg btn-primary">Start Tracking</button>
    </a>
  </div>
</div>

{%- block footer %}
<footer>
	<span class="container-fluid">
		<h4 class="ebay text-center"><a href="https://www.ebay.ca/" target="_blank">Search for products on eBay</a></h4>
  </span>
</footer>
{%- endblock footer %}
{% endblock %}

price_is_now_right/templates/login.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_field %}

{% block title %}
Login | The Price Is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='signin.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('main.index') }}">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if current_user.is_anonymous %}
      <ul class="navbar-nav ml-auto">                
        <li class="nav-item active"><a class="nav-link" href="{{ url_for('main.login') }}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.signup') }}">Sign Up</a></li> 
      </ul>
    {% endif %}    
  </div>
</nav>

<br>

<div class="container-fluid">

  <form class="form-signin" method="POST" action="/login">
    <h2 class="form-signin-heading text-center">Log In</h2>
    {{ form.csrf_token() }}  <!--cross site request forgery token for flask-wtf-->
    {{ render_field(form.username) }} <!--getting info from form fields-->
    {{ render_field(form.password) }}
    {{ render_field(form.remember) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
  </form>

</div>

{%- block footer %}

{%- endblock footer %}
{% endblock %}

price_is_now_right/templates/signup.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_field %}

{% block title %}
Sign Up | The Price is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='signin.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('main.index') }}">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if current_user.is_anonymous %}
      <ul class="navbar-nav ml-auto">                
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.login') }}">Login</a></li>
        <li class="nav-item active"><a class="nav-link" href="{{ url_for('main.signup') }}">Sign Up</a></li> 
      </ul>
    {% endif %}    
  </div>
</nav>

<br>

<div class="container-fluid">

  <form class="form-signin" method="POST" action="/signup">
    <h2 class="form-signin-heading text-center">Sign Up</h2>
    {{ form.csrf_token() }} <!--cross site request forgery token for flask-wtf-->
    {{ render_field(form.username) }}  <!--getting info from form fields-->
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
  </form>

</div>

{%- block footer %}

{%- endblock footer %}
{% endblock %}

price_is_now_right/templates/wishlist.html
{% extends "base.html" %}

{% block title %}
Dashboard | The Price is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='wishlist.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('main.index') }}">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a class="nav-link" href="#">Wishlist</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.logout') }}">Log Out</a></li>
    </ul>
  </div>
</nav>

<br>

<div class="container-fluid" id="products">
    <h2 class='wishlist-title text-center'>My Wishlist ({{ productList|length }} items)</h2>
    {% for product in productList %}
    <br>
    <div class='userProduct text-left'>
        <div class="d-flex justify-content-between">
            <a class='product-title' href="{{ product.productURL }}" target="_blank">{{ product.title|truncate(30) }}</a>
            <h4 class="current-price text-right small">Current Price: ${{ product.currentPrice }}</h4>
        </div>
        <h4 class="budget small">Budget: ${{ product.userBudget }}</h4>
        <div class="d-flex justify-content-between">
            <form class='adjust-budget d-flex' method="POST" action="{{ url_for('main.budget', id=product.id) }}">
                <input class='budget-update input-lg' type="number" id="new_budget" name="new_budget" min="0" max="{{ product.currentPrice }}" step=".01"><br>            
                <input class='budget-update-btn btn btn-primary' type="submit" value="Adjust Budget">
            </form>
            <form class='remove-wishlist' action="{{ url_for('main.delete', id=product.id) }}">
                <button class="btn btn-danger" type="submit">Remove from Wishlist</button>
            </form>
        </div>
        
        {% if loop.index < productList|length %}
        <hr>
        {% endif %}
    </div>
    {% endfor %}
</div>

{%- block footer %}

{%- endblock footer %}

</div>


{% endblock %}

templates/dashboard.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_field %}

{% block title %}
Dashboard | The Price is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='dashboard.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('index') }}">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('wishlist') }}">Wishlist</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('logout') }}">Log Out</a></li>
    </ul>
  </div>
</nav>

<br>

<!-- form for price tracking-->
<div class="container-fluid text-center">
    <form class="form-track" method="POST" onsubmit="change()" method="POST" action="/dashboard">
        {{ form.csrf_token() }}  <!--cross site request forgery token for flask-wtf-->
        {{ render_field(form.url) }} <!--getting info from form fields-->
        {{ render_field(form.userBudget) }}
        <button class="btn btn-primary btn-lg" type="submit" id="enter">Start Price Tracking!</button>
    </form>
    <br>
    <img class="tracker" src="../static/tracker.gif">
</div>

{%- block footer %}

{%- endblock footer %}

<script>
    function change() {
        alert("Price Tracking...\nYou will receive an email once the price goes down!");
    }
</script>

</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
Home | The Price Is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='index.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
{{super()}}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if current_user.is_anonymous %}
      <ul class="navbar-nav ml-auto">                
        <li class="nav-item"><a class="nav-link" href="{{ url_for('login') }}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('signup') }}">Sign Up</a></li> 
      </ul>
    {% endif %}
    {% if current_user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('wishlist') }}">Wishlist</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('logout') }}">Log Out</a></li>
      </ul>
    {% endif %}  
  </div>
</nav>

<br><br><br><br><br><br>
<div class="container-fluid">
  <div class="container-fluid col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <h3 class="describe">Never miss a discount on things you want!</h3>
    <br>
    <a class="start" 
      {% if current_user.is_anonymous %}
      href="{{ url_for('login') }}"
      {% else %}
      href="{{ url_for('dashboard') }}"
      {% endif %}>
      <button class="startbutton btn btn-lg btn-primary">Start Tracking</button>
    </a>
  </div>
</div>

{%- block footer %}
<footer>
	<span class="container-fluid">
		<h4 class="amazon text-center"><a href="https://www.amazon.ca/" target="_blank">Search for products on Amazon</a></h4>
  </span>
</footer>
{%- endblock footer %}
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_field %}

{% block title %}
Login | The Price Is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='signin.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('index') }}">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if current_user.is_anonymous %}
      <ul class="navbar-nav ml-auto">                
        <li class="nav-item active"><a class="nav-link" href="{{ url_for('login') }}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('signup') }}">Sign Up</a></li> 
      </ul>
    {% endif %}    
  </div>
</nav>

<br>

<div class="container-fluid">

  <form class="form-signin" method="POST" action="/login">
    <h2 class="form-signin-heading text-center">Log In</h2>
    {{ form.csrf_token() }}  <!--cross site request forgery token for flask-wtf-->
    {{ render_field(form.username) }} <!--getting info from form fields-->
    {{ render_field(form.password) }}
    {{ render_field(form.remember) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
  </form>

</div>

{%- block footer %}

{%- endblock footer %}
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_field %}

{% block title %}
Sign Up | The Price is Now Right
{% endblock %}

{% block head %}
{{super()}}
{% block favicon %}
<link href="../static/favicon.ico" rel="icon" type="image/x-icon" />
{% endblock %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='signin.css')}}">
<link href="https://fonts.googleapis.com/css?family=Cabin:700&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('index') }}">The Price Is Now Right</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if current_user.is_anonymous %}
      <ul class="navbar-nav ml-auto">                
        <li class="nav-item"><a class="nav-link" href="{{ url_for('login') }}">Login</a></li>
        <li class="nav-item active"><a class="nav-link" href="{{ url_for('signup') }}">Sign Up</a></li> 
      </ul>
    {% endif %}    
  </div>
</nav>

<br>

<div class="container-fluid">

  <form class="form-signin" method="POST" action="/signup">
    <h2 class="form-signin-heading text-center">Sign Up</h2>
    {{ form.csrf_token() }} <!--cross site request forgery token for flask-wtf-->
    {{ render_field(form.username) }}  <!--getting info from form fields-->
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
  </form>

</div>

{%- block footer %}

{%- endblock footer %}
{% endblock %}